// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/grpc/proto/satfarm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerMessage_Hello
	//	*WorkerMessage_JobResult
	Msg           isWorkerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerMessage) Reset() {
	*x = WorkerMessage{}
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerMessage) ProtoMessage() {}

func (x *WorkerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerMessage.ProtoReflect.Descriptor instead.
func (*WorkerMessage) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_satfarm_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerMessage) GetMsg() isWorkerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerMessage) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Msg.(*WorkerMessage_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

type isWorkerMessage_Msg interface {
	isWorkerMessage_Msg()
}

type WorkerMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type WorkerMessage_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,2,opt,name=job_result,json=jobResult,proto3,oneof"`
}

func (*WorkerMessage_Hello) isWorkerMessage_Msg() {}

func (*WorkerMessage_JobResult) isWorkerMessage_Msg() {}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ServerMessage_AssignJob
	//	*ServerMessage_CancelJob
	//	*ServerMessage_Ping
	Msg           isServerMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_satfarm_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetMsg() isServerMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ServerMessage) GetAssignJob() *AssignJob {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_AssignJob); ok {
			return x.AssignJob
		}
	}
	return nil
}

func (x *ServerMessage) GetCancelJob() *CancelJob {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_CancelJob); ok {
			return x.CancelJob
		}
	}
	return nil
}

func (x *ServerMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*ServerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_AssignJob struct {
	AssignJob *AssignJob `protobuf:"bytes,1,opt,name=assign_job,json=assignJob,proto3,oneof"`
}

type ServerMessage_CancelJob struct {
	CancelJob *CancelJob `protobuf:"bytes,2,opt,name=cancel_job,json=cancelJob,proto3,oneof"`
}

type ServerMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,3,opt,name=ping,proto3,oneof"`
}

func (*ServerMessage_AssignJob) isServerMessage_Msg() {}

func (*ServerMessage_CancelJob) isServerMessage_Msg() {}

func (*ServerMessage_Ping) isServerMessage_Msg() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerName    string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	SolverType    string                 `protobuf:"bytes,2,opt,name=solver_type,json=solverType,proto3" json:"solver_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_satfarm_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *Hello) GetSolverType() string {
	if x != nil {
		return x.SolverType
	}
	return ""
}

// Server tells worker: solve original CNF under this cube.
type AssignJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                             // jobs.id
	ShardId       int64                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`                       // job_shards.id
	CubeLiterals  []int32                `protobuf:"varint,3,rep,packed,name=cube_literals,json=cubeLiterals,proto3" json:"cube_literals,omitempty"` // cube for this shard
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignJob) Reset() {
	*x = AssignJob{}
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignJob) ProtoMessage() {}

func (x *AssignJob) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignJob.ProtoReflect.Descriptor instead.
func (*AssignJob) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_satfarm_proto_rawDescGZIP(), []int{3}
}

func (x *AssignJob) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *AssignJob) GetShardId() int64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *AssignJob) GetCubeLiterals() []int32 {
	if x != nil {
		return x.CubeLiterals
	}
	return nil
}

type JobResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           int64                  `protobuf:"varint,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`       // jobs.id
	ShardId         int64                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"` // job_shards.id
	Sat             bool                   `protobuf:"varint,3,opt,name=sat,proto3" json:"sat,omitempty"`
	ModelOrCoreInfo string                 `protobuf:"bytes,4,opt,name=model_or_core_info,json=modelOrCoreInfo,proto3" json:"model_or_core_info,omitempty"` // model or UNSAT info
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_satfarm_proto_rawDescGZIP(), []int{4}
}

func (x *JobResult) GetJobId() int64 {
	if x != nil {
		return x.JobId
	}
	return 0
}

func (x *JobResult) GetShardId() int64 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *JobResult) GetSat() bool {
	if x != nil {
		return x.Sat
	}
	return false
}

func (x *JobResult) GetModelOrCoreInfo() string {
	if x != nil {
		return x.ModelOrCoreInfo
	}
	return ""
}

type CancelJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJob) Reset() {
	*x = CancelJob{}
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJob) ProtoMessage() {}

func (x *CancelJob) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJob.ProtoReflect.Descriptor instead.
func (*CancelJob) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_satfarm_proto_rawDescGZIP(), []int{5}
}

func (x *CancelJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_satfarm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_satfarm_proto_rawDescGZIP(), []int{6}
}

var File_internal_grpc_proto_satfarm_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_satfarm_proto_rawDesc = "" +
	"\n" +
	"!internal/grpc/proto/satfarm.proto\x12\asatfarm\"s\n" +
	"\rWorkerMessage\x12&\n" +
	"\x05hello\x18\x01 \x01(\v2\x0e.satfarm.HelloH\x00R\x05hello\x123\n" +
	"\n" +
	"job_result\x18\x02 \x01(\v2\x12.satfarm.JobResultH\x00R\tjobResultB\x05\n" +
	"\x03msg\"\xa5\x01\n" +
	"\rServerMessage\x123\n" +
	"\n" +
	"assign_job\x18\x01 \x01(\v2\x12.satfarm.AssignJobH\x00R\tassignJob\x123\n" +
	"\n" +
	"cancel_job\x18\x02 \x01(\v2\x12.satfarm.CancelJobH\x00R\tcancelJob\x12#\n" +
	"\x04ping\x18\x03 \x01(\v2\r.satfarm.PingH\x00R\x04pingB\x05\n" +
	"\x03msg\"I\n" +
	"\x05Hello\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12\x1f\n" +
	"\vsolver_type\x18\x02 \x01(\tR\n" +
	"solverType\"b\n" +
	"\tAssignJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x03R\ashardId\x12#\n" +
	"\rcube_literals\x18\x03 \x03(\x05R\fcubeLiterals\"|\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\x03R\x05jobId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x03R\ashardId\x12\x10\n" +
	"\x03sat\x18\x03 \x01(\bR\x03sat\x12+\n" +
	"\x12model_or_core_info\x18\x04 \x01(\tR\x0fmodelOrCoreInfo\"\"\n" +
	"\tCancelJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x06\n" +
	"\x04Ping2K\n" +
	"\rWorkerService\x12:\n" +
	"\x04Work\x12\x16.satfarm.WorkerMessage\x1a\x16.satfarm.ServerMessage(\x010\x01B#Z!satfarm/internal/grpc/proto;protob\x06proto3"

var (
	file_internal_grpc_proto_satfarm_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_satfarm_proto_rawDescData []byte
)

func file_internal_grpc_proto_satfarm_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_satfarm_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_satfarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_satfarm_proto_rawDesc), len(file_internal_grpc_proto_satfarm_proto_rawDesc)))
	})
	return file_internal_grpc_proto_satfarm_proto_rawDescData
}

var file_internal_grpc_proto_satfarm_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_grpc_proto_satfarm_proto_goTypes = []any{
	(*WorkerMessage)(nil), // 0: satfarm.WorkerMessage
	(*ServerMessage)(nil), // 1: satfarm.ServerMessage
	(*Hello)(nil),         // 2: satfarm.Hello
	(*AssignJob)(nil),     // 3: satfarm.AssignJob
	(*JobResult)(nil),     // 4: satfarm.JobResult
	(*CancelJob)(nil),     // 5: satfarm.CancelJob
	(*Ping)(nil),          // 6: satfarm.Ping
}
var file_internal_grpc_proto_satfarm_proto_depIdxs = []int32{
	2, // 0: satfarm.WorkerMessage.hello:type_name -> satfarm.Hello
	4, // 1: satfarm.WorkerMessage.job_result:type_name -> satfarm.JobResult
	3, // 2: satfarm.ServerMessage.assign_job:type_name -> satfarm.AssignJob
	5, // 3: satfarm.ServerMessage.cancel_job:type_name -> satfarm.CancelJob
	6, // 4: satfarm.ServerMessage.ping:type_name -> satfarm.Ping
	0, // 5: satfarm.WorkerService.Work:input_type -> satfarm.WorkerMessage
	1, // 6: satfarm.WorkerService.Work:output_type -> satfarm.ServerMessage
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_satfarm_proto_init() }
func file_internal_grpc_proto_satfarm_proto_init() {
	if File_internal_grpc_proto_satfarm_proto != nil {
		return
	}
	file_internal_grpc_proto_satfarm_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerMessage_Hello)(nil),
		(*WorkerMessage_JobResult)(nil),
	}
	file_internal_grpc_proto_satfarm_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerMessage_AssignJob)(nil),
		(*ServerMessage_CancelJob)(nil),
		(*ServerMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_satfarm_proto_rawDesc), len(file_internal_grpc_proto_satfarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_satfarm_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_satfarm_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_satfarm_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_satfarm_proto = out.File
	file_internal_grpc_proto_satfarm_proto_goTypes = nil
	file_internal_grpc_proto_satfarm_proto_depIdxs = nil
}
